FROM node:20-alpine

# Установка зависимостей
RUN npm install -g pnpm

# Создаем рабочую директорию
WORKDIR /app

# Копируем файлы package.json и pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# Устанавливаем зависимости
RUN pnpm install

# Копируем все файлы проекта
COPY . .

# Запускаем сервер на порту 1000
EXPOSE 1000
CMD ["pnpm", "start", "-p", "1000"] 